In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings ('ignore')

In [2]:
df = sns.load_dataset ('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [3]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [5]:
df.shape

(891, 15)

In [6]:
df.drop (['deck', 'embark_town','alive','class','who', 'adult_male'], axis= 1, inplace= True)

In [7]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True


In [8]:
df['age'].fillna(df['age'].mean(), inplace= True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True


In [9]:
df.dropna (subset= 'embarked', inplace= True)

In [10]:
df.shape

(889, 9)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()

In [14]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [15]:
df.head ()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22.0,1,0,7.2500,2,False
1,1,1,0,38.0,1,0,71.2833,0,False
2,1,3,0,26.0,0,0,7.9250,2,True
3,1,1,0,35.0,1,0,53.1000,2,False
4,0,3,1,35.0,0,0,8.0500,2,True


In [16]:
df.rename(columns={'sex': 'isMale'}, inplace=True)

In [17]:
df.head()

,survived,pclass,isMale,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22.0,1,0,7.2500,2,False
1,1,1,0,38.0,1,0,71.2833,0,False
2,1,3,0,26.0,0,0,7.9250,2,True
3,1,1,0,35.0,1,0,53.1000,2,False
4,0,3,1,35.0,0,0,8.0500,2,True


In [18]:
df = df.astype (int)

In [19]:
df.head()

,survived,pclass,isMale,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22,1,0,7,2,0
1,1,1,0,38,1,0,71,0,0
2,1,3,0,26,0,0,7,2,1
3,1,1,0,35,1,0,53,2,0
4,0,3,1,35,0,0,8,2,1


In [20]:
X = df.drop ('survived', axis= 1)
y = df['survived']

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
model_L = LogisticRegression()

In [25]:
model_L.fit (X_train,y_train)

LogisticRegression()

In [26]:
y_pred = model_L.predict (X_test)

In [27]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [28]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [29]:
  confusion_matrix (y_test, y_pred)

array([[90, 19],
       [16, 53]])

In [31]:
print (classification_report (y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()

In [34]:
X_train_scale = scaler.fit_transform(X_train)
X_train_scale

array([[-1.58410418, -1.40530972, -0.58667407, ...,  2.42752104,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.05336323, ..., -0.35872483,
        -1.95246446, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.17519856, ..., -0.50108776,
         0.58770431,  0.81076671],
       ...,
       [-1.58410418, -1.40530972,  1.39419477, ..., -0.13501166,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.66286134, ...,  0.04802639,
         0.58770431, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.25138582, ..., -0.4807502 ,
         0.58770431,  0.81076671]])

In [36]:
X_test_Scaled = scaler.fit_transform(X_test)
print(X_test_Scaled)

[[ 0.87837838  0.83380939 -0.05614186 ... -0.48065958  0.5836712
   0.82416338]
 [-1.52702703 -1.19931487 -1.19358508 ...  1.70666776  0.5836712
  -1.21335165]
 [ 0.87837838 -1.19931487 -1.19358508 ... -0.40323207 -1.88998295
  -1.21335165]
 ...
 [ 0.87837838 -1.19931487  0.75631758 ... -0.01609448  0.5836712
  -1.21335165]
 [ 0.87837838 -1.19931487  0.35008786 ... -0.32580455  0.5836712
  -1.21335165]
 [ 0.87837838 -1.19931487 -2.00604452 ... -0.30644767  0.5836712
  -1.21335165]]


In [37]:
X_test

,pclass,isMale,age,sibsp,parch,fare,embarked,alone
281,3,1,28,0,0,7,2,1
435,1,0,14,1,2,120,2,0
39,3,0,14,1,0,11,0,0
418,2,1,30,0,0,13,2,1
585,1,0,18,0,2,79,2,0
...,...,...,...,...,...,...,...,...
433,3,1,17,0,0,7,2,1
807,3,0,18,0,0,7,2,1
25,3,0,38,1,5,31,2,0
85,3,0,33,3,0,15,2,0


*KNN

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [41]:
model_KNN = KNeighborsClassifier ( n_neighbors= 5)
model_KNN.fit (X_train_scale, y_train)

KNeighborsClassifier()

In [43]:
y_pred_knn = model_KNN.predict (X_test_Scaled)

In [45]:
accuracy_score (y_test, y_pred_knn)

0.7808988764044944

In [46]:
confusion_matrix(y_test, y_pred_knn)

array([[90, 19],
       [20, 49]])

In [48]:
from sklearn.naive_bayes import GaussianNB

In [49]:
model_NB = GaussianNB()

In [50]:
model_NB.fit (X_train,y_train)

GaussianNB()

In [52]:
y_pred_NB = model_NB.predict (X_test)

In [53]:
accuracy_score (y_test, y_pred_NB)

0.7752808988764045

In [54]:
confusion_matrix (y_test, y_pred_NB)

array([[84, 25],
       [15, 54]])

In [55]:
print (classification_report (y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [56]:
from sklearn.tree import DecisionTreeClassifier

In [57]:
model_DT = DecisionTreeClassifier()

In [59]:
model_DT.fit (X_train_scale,y_train)

DecisionTreeClassifier()

In [61]:
y_pred_DT = model_DT.predict (X_test_Scaled)

In [62]:
accuracy_score (y_test, y_pred_DT)

0.7584269662921348

In [63]:
confusion_matrix (y_test, y_pred_NB)

array([[84, 25],
       [15, 54]])

In [65]:
print (classification_report (y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [66]:
from sklearn.svm import SVC

In [67]:
model_SVM = SVC(kernel= "rbf")

In [68]:
model_SVM.fit (X_train_scale,y_train)

SVC()

In [70]:
y_pred_svm = model_SVM.predict (X_test_Scaled)

In [71]:
accuracy_score (y_test, y_pred_svm)

0.8258426966292135

In [74]:
confusion_matrix (y_test, y_pred_svm)

array([[96, 13],
       [18, 51]])

In [76]:
print (classification_report (y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178

